spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      poll-interval: 5s
      quiet-period: 1s
  jpa:
    show-sql: false
    roperties:
      hibernate:
        format_sql: true
security:
  oauth2:
    client:
      client-id: animes
      client-secret: animes123
jwt:
  secret: MY-JWT-SECRET
  duration: 86400