spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      poll-interval: 5s
      quiet-period: 1s
  jpa:
    show-sql: true
    roperties:
      hibernate:
        format_sql: true